numlockx
remaps
bgs -zR /home/zakaria/.config/wall.png &

autostart="slstatus mpd dunst numlock redshift pipewire"

for program in $autostart; do
	pidof -s "$program" || setsid -f "$program"
done >/dev/null 2>&1

xinput --disable "SynPS/2 Synaptics TouchPad"
exec dwm
